### ISSUE TITLE
bug in method getRefreshAccessToken

### ISSUE THREAD

**Issue by githubamir** [kbariotis/feedly-api#12]
line 119 feedly.php

//@m!r        $refresh_token change to  'refresh_token'
"grant_type" => 'refresh_token'

**Comment by kbariotis** [comment]
Hi @githubamir would you mind give the error you are encountering. I saw in the documentation that it is actually wrong my method but I am thinking maybe there's been an API update so I don't want to make any breaking changes. 

Thank you

**Comment by githubamir** [comment]
thank you for your support

**Comment by kbariotis** [comment]
@githubamir we 've updated and fix the refresh token bug. Please update.
