### ISSUE TITLE
Broken timestamps

### ISSUE THREAD

**Issue by ax23w4** [kbariotis/feedly-api#15]
In HTTPClient, please change line 124 to this one:

        $response = json_decode($response, true, 512, JSON_BIGINT_AS_STRING);

This fixes timestamps being converted to floats on 32-bit systems.

This:
            [published] => 1.42990602E+12
            [crawled] => 1.4299064506E+12
Becomes this:
            [published] => 1429906106000
            [crawled] => 1429906127284

**Comment by kbariotis** [comment]
great @ax23w4.

thank you
