### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by skynet** [kbariotis/feedly-api#31]
if not, can you reccomend another library?

**Comment by kbariotis** [comment]
@skynet unfortunately no as I haven't been using it myself for quite a few years now. Did you try it though and found any issues? Can you please report those and hopefully someone can jump in and contribute. Thank you

**Comment by skynet** [comment]
Haven't started yet, but will do. I was just searching for a good library. Are there all Feedly methods available with this library? Thanks again.

**Comment by kbariotis** [comment]
@skynet Unfortunately, I don't really remember. You can check the README file to see the available methods. Please do at least give it a try and let us know what you have found.

**Comment by skynet** [comment]
I'll definitely give it a try. Closing this for now.
