### ISSUE TITLE
Using Access Token in Feedly-api

### ISSUE THREAD

**Issue by hazemusa** [kbariotis/feedly-api#9]
Hello,

I got a "user id" and "Access Token" from Feedly. I am struggling with re-authentication every now and then while on Sandbox mode.
Is there a way to use those in the API (instead of the of the short-lived) Access Token that Feedly-API gives to be able to work without interruptions??
If not, can you please tell me how to extend the API Access Token so I can finish without getting a new code every few minutes??

Thank you,

Hazemusa

**Comment by deepaktanwar239** [comment]
Hello 
 try to run example profile.php and got
 Fatal error: Class 'feedly\Feedly' not found in /Users/deepaktanwar/Desktop/htdocs/feedly-api-master/example/profile.php on line 11 what wrong with this?

**Comment by kbariotis** [comment]
@deepaktanwar239 maybe the example is broken. Could you please try like this: https://github.com/kbariotis/feedly-api/blob/master/tests/ProfileTest.php#L15?

**Comment by deepaktanwar239** [comment]
Hey,
Can you provide me command to download these file from composer
